### ISSUE TITLE
"may hide script" warning

### ISSUE THREAD

**Issue by mbrowne** [jcoplien/trygve#52]
I wonder if we can do away with these warnings now that trygve no longer allows direct access to Context members from roles:

```
WARNING: Script declaration for `amount' may hide script declared at line 3
```

I get the above warning when compiling the alternative money transfer context I just posted to the group (also pasted below). In this case the warning is potentially more confusing because the whole point of including amount() in the contract of the Transfer role was to _make_ it accessible to the other roles.

```
context TransferMoney {
    private int amount_;
    private int amount() const {
        return amount_;
    }

    public TransferMoney(Account source, Account destination, int amount) {
        SourceAccount = source;
        DestinationAccount = destination;
        amount_ = amount.clone;
        Transfer = this;
    }

    public void run() {
        Transfer.start();
    }

    stageprop Transfer {
        public void start() {
            SourceAccount.withdraw();
            DestinationAccount.deposit();
        }
    }
    requires {
        private int amount() const;
    }

    role SourceAccount {    
        public void withdraw() {
            if (Transfer.amount() > getBalance()) {
                assert(false, "Insufficient funds");
            }
            decreaseBalance(Transfer.amount());
        }
    }
    requires {
        void decreaseBalance(int amt);
        int getBalance();
    }

    role DestinationAccount {
        public void deposit() {
            increaseBalance(Transfer.amount());
        }
    } requires {
        void increaseBalance(int amt)
    }
}

class Account {
    public Account() {
       balance_ = 0;
    }
    private int balance_;

    public void increaseBalance(int amount) {
        balance_ = balance_ + amount
    }

    public void decreaseBalance(int amount) {
        balance_ = balance_ - amount
    }

    public int getBalance() {
        return balance_;
    }
}
```

**Comment by jcoplien** [comment]
> Den 20/01/2016 kl. 02.28 skrev Matt Browne notifications@github.com:
> 
> I wonder if we can do away with these warnings now that trygve no longer allows direct access to Context members from roles:
> 
> WARNING: Script declaration for `amount' may hide script declared at line 3
> Maybe. But those familiar with block-structured languages may still expect the outer one to be called if the inner one is outside their locus of attention. I have learned from the examples that people have written that such blind spots are indeed possible because the Contexts are rather large beasts. This should give us some pause to reflect a bit, because the Contexts I’m seeing are not mental gestalten.

In such a world, one needs tools to point out potential name conflicts. It’s not that a given piece of code will ever call the outer X: it’s that the programmer may only see the outer X in a given moment and presume that a given call will invoke that one rather than one more closely located to the point of invocation in the static chain. So I think the warning is still a good idea.

Overloading names across scopes is a bad idea anyhow and usually reflects a lack of insight, or at least of imagination, in naming things. There are some exceptions such as print, but I’d rather be safe than sorry.

**Comment by mbrowne** [comment]
Good point. It might still help to change the wording of it, e.g. 
"Script declaration for `amount' has the same name as Context script 
declared at line 3". And this is a low priority, but it would be nice if 
the warnings didn't appear at all when calling Context methods via a 
role bound to the current Context, since there's no actual name conflict 
in that case.

**Comment by jcoplien** [comment]
This should be fixed in 1.3.1. Please verify and close the issue.

**Comment by mbrowne** [comment]
Yes, the warning message is more accurate now. It's still appearing for context methods when the context itself is playing a role, even after changing it to use a role method instead of directly calling the instance method (see below), but I can open a new issue about that and as I mentioned above, that's a low priority issue.

```
context TransferMoney {
    private int amount_;
    private int amount() const {
        return amount_;
    }

    public TransferMoney(Account source, Account destination, int amount) {
        SourceAccount = source;
        DestinationAccount = destination;
        amount_ = amount.clone;
        Transfer = this;
    }

    public void run() {
        Transfer.start();
    }

    stageprop Transfer {
        public void start() {
            SourceAccount.withdraw();
            DestinationAccount.deposit();
        }
        public int getAmount() {
            return amount();
        }
    }
    requires {
        private int amount() const;
    }

    role SourceAccount {    
        public void withdraw() {
            if (Transfer.getAmount() > getBalance()) {
                assert(false, "Insufficient funds");
            }
            decreaseBalance(Transfer.getAmount());
        }
    }
    requires {
        void decreaseBalance(int amt);
        int getBalance();
    }

    role DestinationAccount {
        public void deposit() {
            increaseBalance(Transfer.getAmount());
        }
    } requires {
        void increaseBalance(int amt)
    }
}

class Account {
    public Account() {
       balance_ = 0;
    }
    private int balance_;

    public void increaseBalance(int amount) {
        balance_ = balance_ + amount
    }

    public void decreaseBalance(int amount) {
        balance_ = balance_ - amount
    }

    public int getBalance() {
        return balance_;
    }
}
```

**Comment by jcoplien** [comment]
thanks.
